spring:
  # Liquibase properties
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/dev-auth.changelog-master.xml
    contexts: "!test"

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
    producer:
      retries: 3
      acks: all
      properties:
        linger.ms: 5
        enable.idempotence: true

  # Validate schema against hibernate models
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none #create | update | validate | none
#      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties.org.hibernate.envers.store_data_at_delete: true

server:
  port: 8080
  canonical.url: http://localhost:8080/dev-auth
  servlet.context-path: /dev-auth
  name: localhost

security:
  jwt:
    secret: mySecretKeyForJwtToken
    expiration: 3600000 # 1 hour in milliseconds

elastic:
  index:
    private: es_private_message_index
    group: es_group_message_index