spring:
  # Liquibase properties
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/dev-auth.changelog-master.xml
    contexts: "!test"
#    liquibase-schema: public
#    database-change-log-table: DATABASECHANGELOG
#    database-change-log-lock-table: DATABASECHANGELOGLOCK

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
    producer:
      retries: 3
      acks: all
      properties:
        linger.ms: 5
        enable.idempotence: true

  # Validate schema against hibernate models
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none #create | update | validate | none
#      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties.org.hibernate.envers.store_data_at_delete: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv23liap9b0pCJfbCrxs
            client-secret: fd28c44ee0ec0ba7a458fbc7d7c836aa37b36219
            scope: read:user, user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            authorization-grant-type: authorization_code
            client-name: GitHub
          google:
            client-id: 190624024371-5rnr5nhn766nk7okgev8vp126oqpd96d.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

server:
  port: 8080
  address: 0.0.0.0
#  canonical.url: http://localhost:8080/dev-auths
#  servlet.context-path: /dev-auths
  name: localhost

security:
  jwt:
    secret: mySecretKeyForJwtToken
    expiration: 3600000 # 1 hour in milliseconds


elastic:
  index:
    private: es_private_message_index
    group: es_group_message_index